import Head from 'next/head'
import Login from '../components/Login'
import { useRouter } from 'next/router'
import supabase from '../utils/supabase'
import { useState, useEffect } from 'react'
import styles from '../styles/Home.module.css'


export default function Home() {
  const [session, setSession] = useState(null)
  const router = useRouter()

  useEffect(() => {
    setSession(supabase.auth.session())
    console.log(supabase.auth.session())

    supabase.auth.onAuthStateChange((_event, session) => {
      setSession(session)

      console.log(supabase.auth.session())
      console.log('4356f4rg')
    })
  }, [])


  return session ? (
    <></>
  ) : (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Login />
    </div >
  )
}


export async function getClientSideProps(context) {
  console.log(supabase.auth.session())
  console.log('asdf344c')
  return {
    props: {}
  }
}
